# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auma.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 296)
        MainWindow.setStyleSheet("background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #7d7d7d, stop: 0.4 #787878,\n"
"                     stop: 0.5 #616161, stop: 1.0 #464646);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.NewTaskButton = QtWidgets.QPushButton(self.centralwidget)
        self.NewTaskButton.setMinimumSize(QtCore.QSize(250, 40))
        self.NewTaskButton.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.NewTaskButton.setFont(font)
        self.NewTaskButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.NewTaskButton.setObjectName("NewTaskButton")
        self.verticalLayout.addWidget(self.NewTaskButton)
        self.AuftragAnz = QtWidgets.QPushButton(self.centralwidget)
        self.AuftragAnz.setMinimumSize(QtCore.QSize(250, 40))
        self.AuftragAnz.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AuftragAnz.setFont(font)
        self.AuftragAnz.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.AuftragAnz.setObjectName("AuftragAnz")
        self.verticalLayout.addWidget(self.AuftragAnz)
        self.infoChef = QtWidgets.QPushButton(self.centralwidget)
        self.infoChef.setMinimumSize(QtCore.QSize(250, 40))
        self.infoChef.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infoChef.setFont(font)
        self.infoChef.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.infoChef.setObjectName("infoChef")
        self.verticalLayout.addWidget(self.infoChef)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.telefonbuch_but = QtWidgets.QPushButton(self.centralwidget)
        self.telefonbuch_but.setMinimumSize(QtCore.QSize(250, 40))
        self.telefonbuch_but.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.telefonbuch_but.setFont(font)
        self.telefonbuch_but.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.telefonbuch_but.setObjectName("telefonbuch_but")
        self.verticalLayout_2.addWidget(self.telefonbuch_but)
        self.materialmana = QtWidgets.QPushButton(self.centralwidget)
        self.materialmana.setMinimumSize(QtCore.QSize(250, 40))
        self.materialmana.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.materialmana.setFont(font)
        self.materialmana.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.materialmana.setObjectName("materialmana")
        self.verticalLayout_2.addWidget(self.materialmana)
        self.StatsButton = QtWidgets.QPushButton(self.centralwidget)
        self.StatsButton.setMinimumSize(QtCore.QSize(250, 40))
        self.StatsButton.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StatsButton.setFont(font)
        self.StatsButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.StatsButton.setObjectName("StatsButton")
        self.verticalLayout_2.addWidget(self.StatsButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.beendenBut = QtWidgets.QPushButton(self.centralwidget)
        self.beendenBut.setMinimumSize(QtCore.QSize(250, 40))
        self.beendenBut.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.beendenBut.setFont(font)
        self.beendenBut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.beendenBut.setObjectName("beendenBut")
        self.verticalLayout_3.addWidget(self.beendenBut)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hauptmenu"))
        self.NewTaskButton.setText(_translate("MainWindow", "Neuer Auftrag"))
        self.AuftragAnz.setText(_translate("MainWindow", "Aufträge anzeigen"))
        self.infoChef.setText(_translate("MainWindow", "Info für Chef"))
        self.telefonbuch_but.setText(_translate("MainWindow", "Telefonbuch"))
        self.materialmana.setText(_translate("MainWindow", "Materialmanagement"))
        self.StatsButton.setText(_translate("MainWindow", "Hilfsfunktionen anzeigen"))
        self.beendenBut.setText(_translate("MainWindow", "Beenden"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
