# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoDia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoDia(object):
    def setupUi(self, infoDia):
        infoDia.setObjectName("infoDia")
        infoDia.resize(400, 300)
        self.backToMainMenu = QtWidgets.QPushButton(infoDia)
        self.backToMainMenu.setGeometry(QtCore.QRect(300, 250, 75, 23))
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.backToMainMenu.setObjectName("backToMainMenu")

        self.retranslateUi(infoDia)
        QtCore.QMetaObject.connectSlotsByName(infoDia)

    def retranslateUi(self, infoDia):
        _translate = QtCore.QCoreApplication.translate
        infoDia.setWindowTitle(_translate("infoDia", "Dialog"))
        self.backToMainMenu.setText(_translate("infoDia", "Zurück"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infoDia = QtWidgets.QDialog()
    ui = Ui_infoDia()
    ui.setupUi(infoDia)
    infoDia.show()
    sys.exit(app.exec_())
