# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Programmieren\Python\AumaExe-main\Materialmanagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Materialmanagement(object):
    def setupUi(self, Materialmanagement):
        Materialmanagement.setObjectName("Materialmanagement")
        Materialmanagement.resize(718, 655)
        self.verticalLayout = QtWidgets.QVBoxLayout(Materialmanagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Materialmanagement)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.AddButton = QtWidgets.QPushButton(Materialmanagement)
        self.AddButton.setMinimumSize(QtCore.QSize(100, 50))
        self.AddButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout.addWidget(self.AddButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.UpdateButton = QtWidgets.QPushButton(Materialmanagement)
        self.UpdateButton.setMinimumSize(QtCore.QSize(100, 50))
        self.UpdateButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.UpdateButton.setObjectName("UpdateButton")
        self.horizontalLayout.addWidget(self.UpdateButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.delButton = QtWidgets.QPushButton(Materialmanagement)
        self.delButton.setMinimumSize(QtCore.QSize(100, 50))
        self.delButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.delButton.setObjectName("delButton")
        self.horizontalLayout.addWidget(self.delButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.backToMainMenu = QtWidgets.QPushButton(Materialmanagement)
        self.backToMainMenu.setMinimumSize(QtCore.QSize(100, 50))
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.backToMainMenu.setObjectName("backToMainMenu")
        self.horizontalLayout.addWidget(self.backToMainMenu)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Materialmanagement)
        QtCore.QMetaObject.connectSlotsByName(Materialmanagement)

    def retranslateUi(self, Materialmanagement):
        _translate = QtCore.QCoreApplication.translate
        Materialmanagement.setWindowTitle(_translate("Materialmanagement", "Materialmanagement"))
        self.AddButton.setText(_translate("Materialmanagement", "Hinzufügen"))
        self.UpdateButton.setText(_translate("Materialmanagement", "Update"))
        self.delButton.setText(_translate("Materialmanagement", "Löschen"))
        self.backToMainMenu.setText(_translate("Materialmanagement", "Zurück"))
