# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Programmieren\Python\AumaExe-main\materialbestand.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_materialbestand(object):
    def setupUi(self, materialbestand):
        materialbestand.setObjectName("materialbestand")
        materialbestand.resize(1247, 1106)
        materialbestand.setStyleSheet("background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #7d7d7d, stop: 0.4 #787878,\n"
"                     stop: 0.5 #616161, stop: 1.0 #464646);")
        self.gridLayout_2 = QtWidgets.QGridLayout(materialbestand)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.PlusButton = QtWidgets.QPushButton(materialbestand)
        self.PlusButton.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.PlusButton.setFont(font)
        self.PlusButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.PlusButton.setObjectName("PlusButton")
        self.verticalLayout_2.addWidget(self.PlusButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.MinusButton = QtWidgets.QPushButton(materialbestand)
        self.MinusButton.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.MinusButton.setFont(font)
        self.MinusButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.MinusButton.setObjectName("MinusButton")
        self.verticalLayout_2.addWidget(self.MinusButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.FilterBox = QtWidgets.QComboBox(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FilterBox.setFont(font)
        self.FilterBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.FilterBox.setObjectName("FilterBox")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.FilterBox.addItem("")
        self.verticalLayout_2.addWidget(self.FilterBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.BestellenBut = QtWidgets.QPushButton(materialbestand)
        self.BestellenBut.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BestellenBut.setFont(font)
        self.BestellenBut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.BestellenBut.setObjectName("BestellenBut")
        self.verticalLayout.addWidget(self.BestellenBut)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.backToMainMenu = QtWidgets.QPushButton(materialbestand)
        self.backToMainMenu.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.backToMainMenu.setFont(font)
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.backToMainMenu.setObjectName("backToMainMenu")
        self.verticalLayout.addWidget(self.backToMainMenu)
        self.gridLayout_2.addLayout(self.verticalLayout, 9, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.delete2But = QtWidgets.QPushButton(materialbestand)
        self.delete2But.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete2But.setFont(font)
        self.delete2But.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.delete2But.setObjectName("delete2But")
        self.gridLayout.addWidget(self.delete2But, 2, 4, 1, 1)
        self.bestellHinzuBut = QtWidgets.QPushButton(materialbestand)
        self.bestellHinzuBut.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bestellHinzuBut.setFont(font)
        self.bestellHinzuBut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.bestellHinzuBut.setObjectName("bestellHinzuBut")
        self.gridLayout.addWidget(self.bestellHinzuBut, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255,255,255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.li_counter = QtWidgets.QLineEdit(materialbestand)
        self.li_counter.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.li_counter.setFont(font)
        self.li_counter.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.li_counter.setAlignment(QtCore.Qt.AlignCenter)
        self.li_counter.setObjectName("li_counter")
        self.gridLayout.addWidget(self.li_counter, 2, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 6, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem11, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255,255,255)")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 8, 0, 1, 1)
        self.materialtable2 = QtWidgets.QTableWidget(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.materialtable2.setFont(font)
        self.materialtable2.setStyleSheet("background-color:rgb(255,255,255)")
        self.materialtable2.setObjectName("materialtable2")
        self.materialtable2.setColumnCount(8)
        self.materialtable2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable2.setHorizontalHeaderItem(7, item)
        self.gridLayout_2.addWidget(self.materialtable2, 9, 0, 1, 1)
        self.materialtable = QtWidgets.QTableWidget(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.materialtable.setFont(font)
        self.materialtable.setStyleSheet("background-color:rgb(255,255,255)")
        self.materialtable.setObjectName("materialtable")
        self.materialtable.setColumnCount(9)
        self.materialtable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.materialtable.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.materialtable, 4, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.UpdateButton = QtWidgets.QPushButton(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.UpdateButton.setObjectName("UpdateButton")
        self.gridLayout_3.addWidget(self.UpdateButton, 1, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255,255,255)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 3, 1, 1)
        self.GewEdit = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GewEdit.setFont(font)
        self.GewEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.GewEdit.setObjectName("GewEdit")
        self.gridLayout_3.addWidget(self.GewEdit, 2, 3, 1, 1)
        self.FarbeEdit = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FarbeEdit.setFont(font)
        self.FarbeEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.FarbeEdit.setObjectName("FarbeEdit")
        self.gridLayout_3.addWidget(self.FarbeEdit, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(255,255,255)")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 8, 1, 1)
        self.label_8 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255,255,255)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 5, 1, 1)
        self.li_bestellt = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.li_bestellt.setFont(font)
        self.li_bestellt.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.li_bestellt.setObjectName("li_bestellt")
        self.gridLayout_3.addWidget(self.li_bestellt, 2, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255,255,255)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255,255,255)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.ArtEdit = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ArtEdit.setFont(font)
        self.ArtEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.ArtEdit.setObjectName("ArtEdit")
        self.gridLayout_3.addWidget(self.ArtEdit, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255,255,255)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255,255,255)")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255,255,255)")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 7, 1, 1)
        self.DurchBox = QtWidgets.QComboBox(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DurchBox.setFont(font)
        self.DurchBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.DurchBox.setObjectName("DurchBox")
        self.DurchBox.addItem("")
        self.DurchBox.setItemText(0, "")
        self.DurchBox.addItem("")
        self.DurchBox.addItem("")
        self.gridLayout_3.addWidget(self.DurchBox, 2, 2, 1, 1)
        self.delButton = QtWidgets.QPushButton(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delButton.setFont(font)
        self.delButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.delButton.setObjectName("delButton")
        self.gridLayout_3.addWidget(self.delButton, 0, 9, 1, 1)
        self.MatNrEdit = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MatNrEdit.setFont(font)
        self.MatNrEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.MatNrEdit.setObjectName("MatNrEdit")
        self.gridLayout_3.addWidget(self.MatNrEdit, 2, 1, 1, 1)
        self.HerstBox = QtWidgets.QComboBox(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.HerstBox.setFont(font)
        self.HerstBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.HerstBox.setObjectName("HerstBox")
        self.HerstBox.addItem("")
        self.HerstBox.setItemText(0, "")
        self.HerstBox.addItem("")
        self.HerstBox.addItem("")
        self.gridLayout_3.addWidget(self.HerstBox, 2, 6, 1, 1)
        self.li_bestand = QtWidgets.QLineEdit(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.li_bestand.setFont(font)
        self.li_bestand.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.li_bestand.setObjectName("li_bestand")
        self.gridLayout_3.addWidget(self.li_bestand, 2, 7, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 2, 0, 1, 1)
        self.AddButton = QtWidgets.QPushButton(materialbestand)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddButton.setFont(font)
        self.AddButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.AddButton.setObjectName("AddButton")
        self.gridLayout_3.addWidget(self.AddButton, 2, 9, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 3, 0, 1, 1)

        self.retranslateUi(materialbestand)
        QtCore.QMetaObject.connectSlotsByName(materialbestand)

    def retranslateUi(self, materialbestand):
        _translate = QtCore.QCoreApplication.translate
        materialbestand.setWindowTitle(_translate("materialbestand", "Materialbestand"))
        self.PlusButton.setText(_translate("materialbestand", "+"))
        self.MinusButton.setText(_translate("materialbestand", "-"))
        self.label.setText(_translate("materialbestand", "Materialfilter"))
        self.FilterBox.setItemText(0, _translate("materialbestand", "alle"))
        self.FilterBox.setItemText(1, _translate("materialbestand", "PLA"))
        self.FilterBox.setItemText(2, _translate("materialbestand", "PLA-Refill"))
        self.FilterBox.setItemText(3, _translate("materialbestand", "PETG"))
        self.FilterBox.setItemText(4, _translate("materialbestand", "ABS"))
        self.FilterBox.setItemText(5, _translate("materialbestand", "GreenTec"))
        self.FilterBox.setItemText(6, _translate("materialbestand", "Filaflex"))
        self.FilterBox.setItemText(7, _translate("materialbestand", "PC"))
        self.FilterBox.setItemText(8, _translate("materialbestand", "PP"))
        self.FilterBox.setItemText(9, _translate("materialbestand", "sonstige"))
        self.BestellenBut.setText(_translate("materialbestand", "Bestellliste\n"
"bestellen"))
        self.backToMainMenu.setText(_translate("materialbestand", "Zurück"))
        self.delete2But.setText(_translate("materialbestand", "Von Bestellliste \n"
"entfernen"))
        self.bestellHinzuBut.setText(_translate("materialbestand", "Zur Bestellliste \n"
"hinzufügen"))
        self.label_3.setText(_translate("materialbestand", "Menge"))
        self.label_2.setText(_translate("materialbestand", "Bestellliste"))
        item = self.materialtable2.horizontalHeaderItem(0)
        item.setText(_translate("materialbestand", "ID"))
        item = self.materialtable2.horizontalHeaderItem(1)
        item.setText(_translate("materialbestand", "Material Nr."))
        item = self.materialtable2.horizontalHeaderItem(2)
        item.setText(_translate("materialbestand", "Durchmesser"))
        item = self.materialtable2.horizontalHeaderItem(3)
        item.setText(_translate("materialbestand", "Gewicht"))
        item = self.materialtable2.horizontalHeaderItem(4)
        item.setText(_translate("materialbestand", "Art"))
        item = self.materialtable2.horizontalHeaderItem(5)
        item.setText(_translate("materialbestand", "Farbe"))
        item = self.materialtable2.horizontalHeaderItem(6)
        item.setText(_translate("materialbestand", "Hersteller"))
        item = self.materialtable2.horizontalHeaderItem(7)
        item.setText(_translate("materialbestand", "Menge"))
        item = self.materialtable.horizontalHeaderItem(0)
        item.setText(_translate("materialbestand", "ID"))
        item = self.materialtable.horizontalHeaderItem(1)
        item.setText(_translate("materialbestand", "Material Nr."))
        item = self.materialtable.horizontalHeaderItem(2)
        item.setText(_translate("materialbestand", "D"))
        item = self.materialtable.horizontalHeaderItem(3)
        item.setText(_translate("materialbestand", "Gewicht"))
        item = self.materialtable.horizontalHeaderItem(4)
        item.setText(_translate("materialbestand", "Art"))
        item = self.materialtable.horizontalHeaderItem(5)
        item.setText(_translate("materialbestand", "Farbe"))
        item = self.materialtable.horizontalHeaderItem(6)
        item.setText(_translate("materialbestand", "Hersteller"))
        item = self.materialtable.horizontalHeaderItem(7)
        item.setText(_translate("materialbestand", "Bestand"))
        item = self.materialtable.horizontalHeaderItem(8)
        item.setText(_translate("materialbestand", "Bestellt"))
        self.UpdateButton.setText(_translate("materialbestand", "Material Aktualisieren"))
        self.label_6.setText(_translate("materialbestand", "Gewicht"))
        self.label_12.setText(_translate("materialbestand", "Bestellt"))
        self.label_8.setText(_translate("materialbestand", "Farbe"))
        self.label_7.setText(_translate("materialbestand", "Art"))
        self.label_5.setText(_translate("materialbestand", "<html><head/><body><p>Ø</p></body></html>"))
        self.label_4.setText(_translate("materialbestand", "Material Nr."))
        self.label_9.setText(_translate("materialbestand", "Hersteller"))
        self.label_10.setText(_translate("materialbestand", "Bestand"))
        self.DurchBox.setItemText(1, _translate("materialbestand", "1,75"))
        self.DurchBox.setItemText(2, _translate("materialbestand", "2,85"))
        self.delButton.setText(_translate("materialbestand", "Material Löschen"))
        self.HerstBox.setItemText(1, _translate("materialbestand", "Filamentworld"))
        self.HerstBox.setItemText(2, _translate("materialbestand", "Das Filament"))
        self.AddButton.setText(_translate("materialbestand", "Neues Material \n"
"zum Bestand hinzufügen"))
