# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewTask(object):
    def setupUi(self, NewTask):
        NewTask.setObjectName("NewTask")
        NewTask.resize(1468, 842)
        NewTask.setStyleSheet("background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #7d7d7d, stop: 0.4 #787878,\n"
"                     stop: 0.5 #616161, stop: 1.0 #464646);")
        self.gridLayout_3 = QtWidgets.QGridLayout(NewTask)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(NewTask)
        self.tableWidget.setStyleSheet("background-color:rgb(255,255,255)")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 1, 5, 1)
        self.frame = QtWidgets.QFrame(NewTask)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.ANummer = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ANummer.setFont(font)
        self.ANummer.setStyleSheet("color:rgb(255,255,255)")
        self.ANummer.setAlignment(QtCore.Qt.AlignCenter)
        self.ANummer.setObjectName("ANummer")
        self.gridLayout_4.addWidget(self.ANummer, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255,255,255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.calendarBegin = QtWidgets.QCalendarWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        self.calendarBegin.setFont(font)
        self.calendarBegin.setStyleSheet("background-color:rgb(255,255,255)")
        self.calendarBegin.setObjectName("calendarBegin")
        self.verticalLayout_2.addWidget(self.calendarBegin)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255,255,255)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.calendarWish = QtWidgets.QCalendarWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        self.calendarWish.setFont(font)
        self.calendarWish.setStyleSheet("background-color:rgb(255,255,255)")
        self.calendarWish.setObjectName("calendarWish")
        self.verticalLayout_3.addWidget(self.calendarWish)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255,255,255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.radioJa = QtWidgets.QRadioButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.radioJa.setFont(font)
        self.radioJa.setStyleSheet("color:rgb(255,255,255)")
        self.radioJa.setObjectName("radioJa")
        self.gridLayout_5.addWidget(self.radioJa, 3, 0, 1, 1)
        self.radioNein = QtWidgets.QRadioButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.radioNein.setFont(font)
        self.radioNein.setStyleSheet("color:rgb(255,255,255)")
        self.radioNein.setObjectName("radioNein")
        self.gridLayout_5.addWidget(self.radioNein, 5, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem9, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(NewTask)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(255,255,255)")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.l_Bauteil = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.l_Bauteil.setFont(font)
        self.l_Bauteil.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Bauteil.setObjectName("l_Bauteil")
        self.verticalLayout_9.addWidget(self.l_Bauteil)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(255,255,255)")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.t_bauteil = QtWidgets.QTextEdit(self.frame_3)
        self.t_bauteil.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.t_bauteil.setFont(font)
        self.t_bauteil.setStyleSheet("background-color:rgb(255,255,255)")
        self.t_bauteil.setObjectName("t_bauteil")
        self.verticalLayout_10.addWidget(self.t_bauteil)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(255,255,255)")
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(255,255,255)")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(255,255,255)")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 1, 1, 1)
        self.c_material = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.c_material.setFont(font)
        self.c_material.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.c_material.setObjectName("c_material")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.c_material.addItem("")
        self.gridLayout_2.addWidget(self.c_material, 5, 0, 1, 1)
        self.c_vorlage = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.c_vorlage.setFont(font)
        self.c_vorlage.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.c_vorlage.setObjectName("c_vorlage")
        self.c_vorlage.addItem("")
        self.c_vorlage.addItem("")
        self.c_vorlage.addItem("")
        self.c_vorlage.addItem("")
        self.c_vorlage.addItem("")
        self.gridLayout_2.addWidget(self.c_vorlage, 3, 0, 1, 1)
        self.c_farbe = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.c_farbe.setFont(font)
        self.c_farbe.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.c_farbe.setObjectName("c_farbe")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.c_farbe.addItem("")
        self.gridLayout_2.addWidget(self.c_farbe, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(255,255,255)")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.c_fertbereich = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.c_fertbereich.setFont(font)
        self.c_fertbereich.setStyleSheet("QComboBox {\n"
"    border: 1px solid;\n"
"    border-color:rgb(46, 87, 143);\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QComboBox:hover {\n"
"    border-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                                 stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                                stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.c_fertbereich.setObjectName("c_fertbereich")
        self.c_fertbereich.addItem("")
        self.c_fertbereich.addItem("")
        self.c_fertbereich.addItem("")
        self.c_fertbereich.addItem("")
        self.c_fertbereich.addItem("")
        self.gridLayout_2.addWidget(self.c_fertbereich, 3, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255,255,255)")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.s_stuck = QtWidgets.QSpinBox(self.frame_3)
        self.s_stuck.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.s_stuck.setFont(font)
        self.s_stuck.setStyleSheet("background-color:rgb(255,255,255)")
        self.s_stuck.setMaximum(9999)
        self.s_stuck.setObjectName("s_stuck")
        self.verticalLayout_5.addWidget(self.s_stuck)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(NewTask)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.l_Telefon = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Telefon.setFont(font)
        self.l_Telefon.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Telefon.setObjectName("l_Telefon")
        self.gridLayout.addWidget(self.l_Telefon, 2, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255,255,255)")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255,255,255)")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 5, 1, 1)
        self.l_Vorname = QtWidgets.QLineEdit(self.frame_2)
        self.l_Vorname.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Vorname.setFont(font)
        self.l_Vorname.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Vorname.setObjectName("l_Vorname")
        self.gridLayout.addWidget(self.l_Vorname, 2, 1, 1, 1)
        self.l_Kostenstelle = QtWidgets.QLineEdit(self.frame_2)
        self.l_Kostenstelle.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Kostenstelle.setFont(font)
        self.l_Kostenstelle.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Kostenstelle.setObjectName("l_Kostenstelle")
        self.gridLayout.addWidget(self.l_Kostenstelle, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255,255,255)")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.l_Abteilung = QtWidgets.QLineEdit(self.frame_2)
        self.l_Abteilung.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Abteilung.setFont(font)
        self.l_Abteilung.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Abteilung.setObjectName("l_Abteilung")
        self.gridLayout.addWidget(self.l_Abteilung, 2, 3, 1, 1)
        self.l_Nachname = QtWidgets.QLineEdit(self.frame_2)
        self.l_Nachname.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Nachname.setFont(font)
        self.l_Nachname.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Nachname.setObjectName("l_Nachname")
        self.gridLayout.addWidget(self.l_Nachname, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(255,255,255)")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 6, 1, 1)
        self.l_Email = QtWidgets.QLineEdit(self.frame_2)
        self.l_Email.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.l_Email.setFont(font)
        self.l_Email.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_Email.setObjectName("l_Email")
        self.gridLayout.addWidget(self.l_Email, 2, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255,255,255)")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255,255,255)")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem15 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem15)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.callChange = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.callChange.setFont(font)
        self.callChange.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.callChange.setObjectName("callChange")
        self.horizontalLayout_2.addWidget(self.callChange)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem18, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.save_task = QtWidgets.QPushButton(NewTask)
        self.save_task.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_task.setFont(font)
        self.save_task.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.save_task.setDefault(False)
        self.save_task.setFlat(False)
        self.save_task.setObjectName("save_task")
        self.horizontalLayout_5.addWidget(self.save_task)
        self.saveandnew = QtWidgets.QPushButton(NewTask)
        self.saveandnew.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveandnew.setFont(font)
        self.saveandnew.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.saveandnew.setObjectName("saveandnew")
        self.horizontalLayout_5.addWidget(self.saveandnew)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.backToMainMenu = QtWidgets.QPushButton(NewTask)
        self.backToMainMenu.setMinimumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.backToMainMenu.setFont(font)
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.backToMainMenu.setObjectName("backToMainMenu")
        self.horizontalLayout_5.addWidget(self.backToMainMenu)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 5, 0, 1, 2)

        self.retranslateUi(NewTask)
        QtCore.QMetaObject.connectSlotsByName(NewTask)
        NewTask.setTabOrder(self.calendarBegin, self.calendarWish)
        NewTask.setTabOrder(self.calendarWish, self.l_Vorname)
        NewTask.setTabOrder(self.l_Vorname, self.l_Abteilung)
        NewTask.setTabOrder(self.l_Abteilung, self.l_Kostenstelle)
        NewTask.setTabOrder(self.l_Kostenstelle, self.l_Telefon)
        NewTask.setTabOrder(self.l_Telefon, self.l_Email)
        NewTask.setTabOrder(self.l_Email, self.l_Bauteil)
        NewTask.setTabOrder(self.l_Bauteil, self.t_bauteil)
        NewTask.setTabOrder(self.t_bauteil, self.s_stuck)
        NewTask.setTabOrder(self.s_stuck, self.c_vorlage)
        NewTask.setTabOrder(self.c_vorlage, self.c_fertbereich)
        NewTask.setTabOrder(self.c_fertbereich, self.c_material)
        NewTask.setTabOrder(self.c_material, self.c_farbe)
        NewTask.setTabOrder(self.c_farbe, self.save_task)
        NewTask.setTabOrder(self.save_task, self.saveandnew)
        NewTask.setTabOrder(self.saveandnew, self.backToMainMenu)

    def retranslateUi(self, NewTask):
        _translate = QtCore.QCoreApplication.translate
        NewTask.setWindowTitle(_translate("NewTask", "Neuer Auftrag"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("NewTask", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("NewTask", "Nachname"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("NewTask", "Vorname"))
        self.label.setText(_translate("NewTask", "Auftrag Nr."))
        self.ANummer.setText(_translate("NewTask", "NrLabel"))
        self.label_3.setText(_translate("NewTask", "Eingangsdatum"))
        self.label_4.setText(_translate("NewTask", "Wunschtermin"))
        self.label_2.setText(_translate("NewTask", "Eilig"))
        self.radioJa.setText(_translate("NewTask", "Ja"))
        self.radioNein.setText(_translate("NewTask", "Nein"))
        self.label_14.setText(_translate("NewTask", "Bauteil"))
        self.label_17.setText(_translate("NewTask", "Beschreibung"))
        self.label_15.setText(_translate("NewTask", "Vorlage"))
        self.label_18.setText(_translate("NewTask", "Material"))
        self.label_19.setText(_translate("NewTask", "Farbe"))
        self.c_material.setItemText(0, _translate("NewTask", "PLA"))
        self.c_material.setItemText(1, _translate("NewTask", "PLA+"))
        self.c_material.setItemText(2, _translate("NewTask", "PETG"))
        self.c_material.setItemText(3, _translate("NewTask", "GreenTec"))
        self.c_material.setItemText(4, _translate("NewTask", "Nylon GF"))
        self.c_material.setItemText(5, _translate("NewTask", "Nylon CF"))
        self.c_material.setItemText(6, _translate("NewTask", "Filaflex"))
        self.c_vorlage.setItemText(0, _translate("NewTask", "Skizze"))
        self.c_vorlage.setItemText(1, _translate("NewTask", "Zeichnung"))
        self.c_vorlage.setItemText(2, _translate("NewTask", "Musterteil"))
        self.c_vorlage.setItemText(3, _translate("NewTask", "CAD"))
        self.c_vorlage.setItemText(4, _translate("NewTask", "KVS"))
        self.c_farbe.setItemText(0, _translate("NewTask", "egal"))
        self.c_farbe.setItemText(1, _translate("NewTask", "Schwarz"))
        self.c_farbe.setItemText(2, _translate("NewTask", "Weiß"))
        self.c_farbe.setItemText(3, _translate("NewTask", "Silber"))
        self.c_farbe.setItemText(4, _translate("NewTask", "Blau"))
        self.c_farbe.setItemText(5, _translate("NewTask", "Gelb"))
        self.c_farbe.setItemText(6, _translate("NewTask", "Grün"))
        self.c_farbe.setItemText(7, _translate("NewTask", "Rot"))
        self.c_farbe.setItemText(8, _translate("NewTask", "Farblos"))
        self.label_13.setText(_translate("NewTask", "Fertigungsbereich"))
        self.c_fertbereich.setItemText(0, _translate("NewTask", "nicht Vorgewählt"))
        self.c_fertbereich.setItemText(1, _translate("NewTask", "FB1"))
        self.c_fertbereich.setItemText(2, _translate("NewTask", "FB2"))
        self.c_fertbereich.setItemText(3, _translate("NewTask", "FB3"))
        self.c_fertbereich.setItemText(4, _translate("NewTask", "sonstige"))
        self.label_20.setText(_translate("NewTask", "Stückzahl"))
        self.label_9.setText(_translate("NewTask", "Abteilung"))
        self.label_11.setText(_translate("NewTask", "Telefon"))
        self.label_7.setText(_translate("NewTask", "Nachname"))
        self.label_12.setText(_translate("NewTask", "EMail"))
        self.label_10.setText(_translate("NewTask", "Kostenstelle"))
        self.label_8.setText(_translate("NewTask", "Vorname"))
        self.callChange.setText(_translate("NewTask", "Änderungen übernehmen"))
        self.save_task.setText(_translate("NewTask", "Übernehmen"))
        self.saveandnew.setText(_translate("NewTask", "Übernehmen \n"
"und \n"
"weiterer Auftrag"))
        self.backToMainMenu.setText(_translate("NewTask", "Zurück"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewTask = QtWidgets.QDialog()
    ui = Ui_NewTask()
    ui.setupUi(NewTask)
    NewTask.show()
    sys.exit(app.exec_())
