# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Optionen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1685, 948)
        Dialog.setStyleSheet("background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #7d7d7d, stop: 0.4 #787878,\n"
"                     stop: 0.5 #616161, stop: 1.0 #464646);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.backToMainMenu = QtWidgets.QPushButton(Dialog)
        self.backToMainMenu.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.backToMainMenu.setFont(font)
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.backToMainMenu.setObjectName("backToMainMenu")
        self.horizontalLayout_2.addWidget(self.backToMainMenu)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout_6.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 0, 1, 1)
        self.colorchange = QtWidgets.QPushButton(self.tab)
        self.colorchange.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.colorchange.setFont(font)
        self.colorchange.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.colorchange.setObjectName("colorchange")
        self.gridLayout_6.addWidget(self.colorchange, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 3, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setStyleSheet("color:rgb(255,255,255)")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinBoxL3 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxL3.setFont(font)
        self.spinBoxL3.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxL3.setObjectName("spinBoxL3")
        self.gridLayout_3.addWidget(self.spinBoxL3, 1, 6, 1, 1)
        self.spinBoxU2 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxU2.setFont(font)
        self.spinBoxU2.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxU2.setObjectName("spinBoxU2")
        self.gridLayout_3.addWidget(self.spinBoxU2, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setStyleSheet("color:rgb(255,255,255)")
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 15, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setStyleSheet("color:rgb(255,255,255)")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setStyleSheet("color:rgb(255,255,255)")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 3, 1, 1)
        self.fontComboBox2 = QtWidgets.QFontComboBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fontComboBox2.setFont(font)
        self.fontComboBox2.setStyleSheet("background-color:rgb(255,255,255)")
        self.fontComboBox2.setObjectName("fontComboBox2")
        self.gridLayout_3.addWidget(self.fontComboBox2, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setStyleSheet("color:rgb(255,255,255)")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.spinBoxU1 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxU1.setFont(font)
        self.spinBoxU1.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxU1.setProperty("showGroupSeparator", False)
        self.spinBoxU1.setProperty("value", 8)
        self.spinBoxU1.setObjectName("spinBoxU1")
        self.gridLayout_3.addWidget(self.spinBoxU1, 1, 1, 1, 1)
        self.spinBoxL1 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxL1.setFont(font)
        self.spinBoxL1.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxL1.setObjectName("spinBoxL1")
        self.gridLayout_3.addWidget(self.spinBoxL1, 1, 4, 1, 1)
        self.spinBoxL2 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxL2.setFont(font)
        self.spinBoxL2.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxL2.setObjectName("spinBoxL2")
        self.gridLayout_3.addWidget(self.spinBoxL2, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setStyleSheet("color:rgb(255,255,255)")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.fontComboBox1 = QtWidgets.QFontComboBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fontComboBox1.setFont(font)
        self.fontComboBox1.setStyleSheet("background-color:rgb(255,255,255)")
        self.fontComboBox1.setObjectName("fontComboBox1")
        self.gridLayout_3.addWidget(self.fontComboBox1, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setStyleSheet("color:rgb(255,255,255)")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setStyleSheet("color:rgb(255,255,255)")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.fontComboBox3 = QtWidgets.QFontComboBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fontComboBox3.setFont(font)
        self.fontComboBox3.setStyleSheet("background-color:rgb(255,255,255)")
        self.fontComboBox3.setObjectName("fontComboBox3")
        self.gridLayout_3.addWidget(self.fontComboBox3, 3, 0, 1, 1)
        self.spinBoxB1 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxB1.setFont(font)
        self.spinBoxB1.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxB1.setObjectName("spinBoxB1")
        self.gridLayout_3.addWidget(self.spinBoxB1, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setStyleSheet("color:rgb(255,255,255)")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setStyleSheet("color:rgb(255,255,255)")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        self.spinBoxB2 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxB2.setFont(font)
        self.spinBoxB2.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxB2.setObjectName("spinBoxB2")
        self.gridLayout_3.addWidget(self.spinBoxB2, 3, 2, 1, 1)
        self.spinBoxB3 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxB3.setFont(font)
        self.spinBoxB3.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxB3.setObjectName("spinBoxB3")
        self.gridLayout_3.addWidget(self.spinBoxB3, 3, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setStyleSheet("color:rgb(255,255,255)")
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 3, 1, 1)
        self.fontComboBox4 = QtWidgets.QFontComboBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fontComboBox4.setFont(font)
        self.fontComboBox4.setStyleSheet("background-color:rgb(255,255,255)")
        self.fontComboBox4.setObjectName("fontComboBox4")
        self.gridLayout_3.addWidget(self.fontComboBox4, 3, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setStyleSheet("color:rgb(255,255,255)")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setStyleSheet("color:rgb(255,255,255)")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 5, 1, 1)
        self.spinBoxT1 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxT1.setFont(font)
        self.spinBoxT1.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxT1.setObjectName("spinBoxT1")
        self.gridLayout_3.addWidget(self.spinBoxT1, 3, 5, 1, 1)
        self.spinBoxT2 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxT2.setFont(font)
        self.spinBoxT2.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxT2.setObjectName("spinBoxT2")
        self.gridLayout_3.addWidget(self.spinBoxT2, 3, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setStyleSheet("color:rgb(255,255,255)")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setStyleSheet("color:rgb(255,255,255)")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 7, 1, 1)
        self.spinBoxT3 = QtWidgets.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBoxT3.setFont(font)
        self.spinBoxT3.setStyleSheet("background-color:rgb(255,255,255)")
        self.spinBoxT3.setObjectName("spinBoxT3")
        self.gridLayout_3.addWidget(self.spinBoxT3, 3, 7, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LE_Aufpreisfaktor = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Aufpreisfaktor.sizePolicy().hasHeightForWidth())
        self.LE_Aufpreisfaktor.setSizePolicy(sizePolicy)
        self.LE_Aufpreisfaktor.setMinimumSize(QtCore.QSize(150, 0))
        self.LE_Aufpreisfaktor.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.LE_Aufpreisfaktor.setFont(font)
        self.LE_Aufpreisfaktor.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.LE_Aufpreisfaktor.setObjectName("LE_Aufpreisfaktor")
        self.gridLayout_4.addWidget(self.LE_Aufpreisfaktor, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setMinimumSize(QtCore.QSize(250, 0))
        self.label.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255)")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.LE_Arbeitsstunde = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Arbeitsstunde.sizePolicy().hasHeightForWidth())
        self.LE_Arbeitsstunde.setSizePolicy(sizePolicy)
        self.LE_Arbeitsstunde.setMinimumSize(QtCore.QSize(150, 0))
        self.LE_Arbeitsstunde.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.LE_Arbeitsstunde.setFont(font)
        self.LE_Arbeitsstunde.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.LE_Arbeitsstunde.setObjectName("LE_Arbeitsstunde")
        self.gridLayout_4.addWidget(self.LE_Arbeitsstunde, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 2, 1, 1)
        self.LE_Maschinenstunde = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_Maschinenstunde.sizePolicy().hasHeightForWidth())
        self.LE_Maschinenstunde.setSizePolicy(sizePolicy)
        self.LE_Maschinenstunde.setMinimumSize(QtCore.QSize(150, 0))
        self.LE_Maschinenstunde.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.LE_Maschinenstunde.setFont(font)
        self.LE_Maschinenstunde.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.LE_Maschinenstunde.setObjectName("LE_Maschinenstunde")
        self.gridLayout_4.addWidget(self.LE_Maschinenstunde, 0, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setMinimumSize(QtCore.QSize(250, 0))
        self.label_18.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(255,255,255)")
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setMinimumSize(QtCore.QSize(250, 0))
        self.label_15.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:rgb(255,255,255)")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.But_SaveSysVar = QtWidgets.QPushButton(self.tab_2)
        self.But_SaveSysVar.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.But_SaveSysVar.setFont(font)
        self.But_SaveSysVar.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.But_SaveSysVar.setObjectName("But_SaveSysVar")
        self.verticalLayout.addWidget(self.But_SaveSysVar)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem15, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_12.addWidget(self.pushButton_8, 0, 5, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem16, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(800, 30))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_12.addWidget(self.lineEdit_12, 0, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(800, 30))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_12.addWidget(self.lineEdit_18, 2, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_12.addWidget(self.pushButton_9, 1, 5, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_12.addWidget(self.pushButton_12, 2, 7, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_2)
        self.label_41.setMinimumSize(QtCore.QSize(250, 0))
        self.label_41.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color:rgb(255,255,255)")
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 2, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(800, 30))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_12.addWidget(self.lineEdit_17, 1, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_12.addWidget(self.pushButton_10, 2, 5, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem17, 0, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_2)
        self.label_33.setMinimumSize(QtCore.QSize(250, 0))
        self.label_33.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color:rgb(255,255,255)")
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setMinimumSize(QtCore.QSize(250, 0))
        self.label_40.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:rgb(255,255,255)")
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 1, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem18, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem19)
        self.label_39 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:rgb(255,255,255)")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.label_39)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_9.addWidget(self.lineEdit_14, 4, 4, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem21, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_2)
        self.label_34.setMinimumSize(QtCore.QSize(250, 0))
        self.label_34.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color:rgb(255,255,255)")
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 4, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem22, 2, 3, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_9.addWidget(self.lineEdit_13, 2, 4, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_2)
        self.label_32.setMinimumSize(QtCore.QSize(250, 0))
        self.label_32.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color:rgb(255,255,255)")
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 2, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem23, 2, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem24)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:rgb(255,255,255)")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_6.addWidget(self.label_37)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem25)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem26, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_2)
        self.label_35.setMinimumSize(QtCore.QSize(250, 0))
        self.label_35.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:rgb(255,255,255)")
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 1, 1, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem27, 1, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_10.addWidget(self.lineEdit_15, 1, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem28, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem29)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color:rgb(255,255,255)")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_7.addWidget(self.label_38)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem30)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem31, 0, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_11.addWidget(self.lineEdit_16, 0, 3, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem32, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setMinimumSize(QtCore.QSize(250, 0))
        self.label_36.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:rgb(255,255,255)")
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 0, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem33, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_11)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem34)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem35)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem36)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem37)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setMinimumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 6, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:rgb(255,255,255)")
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 1, 2, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem38, 2, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:rgb(255,255,255)")
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 1, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_8.addWidget(self.lineEdit_9, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(255,255,255)")
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_8.addWidget(self.lineEdit_10, 3, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem39, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:rgb(255,255,255)")
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:rgb(255,255,255)")
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 5, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_11.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_8.addWidget(self.lineEdit_11, 5, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_7.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_7.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(255,255,255)")
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 1, 1, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem40, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_7.addWidget(self.lineEdit, 2, 2, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem41, 7, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(255,255,255)")
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 1, 2, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem42, 2, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255,255,255)")
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 6, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_7.addWidget(self.lineEdit_2, 2, 6, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem43, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(255,255,255)")
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 3, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_7.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255,255,255)")
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(255,255,255)")
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 5, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_7.addWidget(self.lineEdit_7, 6, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_7.addWidget(self.lineEdit_8, 6, 6, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(255,255,255)")
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 5, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:rgb(255,255,255)")
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 5, 6, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setStyleSheet("background-color:rgb(255,255,255)")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem44, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.findButton = QtWidgets.QPushButton(self.tab_3)
        self.findButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.findButton.setFont(font)
        self.findButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.findButton.setObjectName("findButton")
        self.gridLayout_2.addWidget(self.findButton, 0, 2, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.tab_3)
        self.connectButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_2.addWidget(self.connectButton, 2, 0, 1, 1)
        self.emailButton = QtWidgets.QPushButton(self.tab_3)
        self.emailButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.emailButton.setFont(font)
        self.emailButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.emailButton.setObjectName("emailButton")
        self.gridLayout_2.addWidget(self.emailButton, 1, 0, 1, 1)
        self.closeConButton = QtWidgets.QPushButton(self.tab_3)
        self.closeConButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.closeConButton.setFont(font)
        self.closeConButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.closeConButton.setObjectName("closeConButton")
        self.gridLayout_2.addWidget(self.closeConButton, 2, 2, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.tab_3)
        self.openButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.openButton.setFont(font)
        self.openButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.openButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.openButton.setObjectName("openButton")
        self.gridLayout_2.addWidget(self.openButton, 0, 0, 1, 1)
        self.LoadButton = QtWidgets.QPushButton(self.tab_3)
        self.LoadButton.setMinimumSize(QtCore.QSize(80, 70))
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoadButton.setFont(font)
        self.LoadButton.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.LoadButton.setObjectName("LoadButton")
        self.gridLayout_2.addWidget(self.LoadButton, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem45, 2, 1, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem46, 0, 0, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem47, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Optionen"))
        self.backToMainMenu.setText(_translate("Dialog", "Zurück"))
        self.colorchange.setText(_translate("Dialog", "Farben übernehmen"))
        self.label_8.setText(_translate("Dialog", "Button"))
        self.label_16.setText(_translate("Dialog", "Label 3"))
        self.pushButton.setText(_translate("Dialog", "Übernehmen"))
        self.label_6.setText(_translate("Dialog", "Label 2"))
        self.label_7.setText(_translate("Dialog", "Label"))
        self.label_2.setText(_translate("Dialog", "Überschrift 2"))
        self.label_5.setText(_translate("Dialog", "Überschrift"))
        self.label_4.setText(_translate("Dialog", "Label 1"))
        self.label_3.setText(_translate("Dialog", "Überschrift 1"))
        self.label_9.setText(_translate("Dialog", "Button 1"))
        self.label_10.setText(_translate("Dialog", "Button 2"))
        self.label_17.setText(_translate("Dialog", "Button 3"))
        self.label_11.setText(_translate("Dialog", "Text"))
        self.label_12.setText(_translate("Dialog", "Text 1"))
        self.label_13.setText(_translate("Dialog", "Text 2"))
        self.label_14.setText(_translate("Dialog", "Text 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Optik"))
        self.label.setText(_translate("Dialog", "Maschinenstunde"))
        self.label_18.setText(_translate("Dialog", "Aufpreisfaktor"))
        self.label_15.setText(_translate("Dialog", "Arbeitsstunde"))
        self.But_SaveSysVar.setText(_translate("Dialog", "Übernehmen"))
        self.pushButton_8.setText(_translate("Dialog", "Ändern"))
        self.pushButton_9.setText(_translate("Dialog", "Ändern"))
        self.pushButton_12.setText(_translate("Dialog", "Übernehmen"))
        self.label_41.setText(_translate("Dialog", "Auftragsbilder"))
        self.pushButton_10.setText(_translate("Dialog", "Ändern"))
        self.label_33.setText(_translate("Dialog", "Auftragsdaten"))
        self.label_40.setText(_translate("Dialog", "Auftragsprogramm"))
        self.label_39.setText(_translate("Dialog", "Allgemein FA-Beleg"))
        self.label_34.setText(_translate("Dialog", "AP"))
        self.label_32.setText(_translate("Dialog", "AFO"))
        self.label_37.setText(_translate("Dialog", "Prusa MKS3+"))
        self.label_35.setText(_translate("Dialog", "APL"))
        self.label_38.setText(_translate("Dialog", "HP"))
        self.label_36.setText(_translate("Dialog", "APL"))
        self.pushButton_7.setText(_translate("Dialog", "Übernehmen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Systemvariablen"))
        self.pushButton_5.setText(_translate("Dialog", "Übernehmen"))
        self.label_30.setText(_translate("Dialog", "Datum"))
        self.label_29.setText(_translate("Dialog", "Ablaufdatum"))
        self.label_28.setText(_translate("Dialog", "Neuer Lizenzschlüssel"))
        self.label_27.setText(_translate("Dialog", "Aktueller Lizenzschlüssel"))
        self.label_31.setText(_translate("Dialog", "Lizenzschlüssel generieren"))
        self.pushButton_6.setText(_translate("Dialog", "Generieren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Lizenz"))
        self.label_21.setText(_translate("Dialog", "ID"))
        self.label_19.setText(_translate("Dialog", "Materialart"))
        self.label_20.setText(_translate("Dialog", "Durchmesser"))
        self.label_23.setText(_translate("Dialog", "Preis"))
        self.label_22.setText(_translate("Dialog", "Gewicht"))
        self.label_24.setText(_translate("Dialog", "Var1"))
        self.label_25.setText(_translate("Dialog", "Var2"))
        self.label_26.setText(_translate("Dialog", "Var3"))
        self.pushButton_4.setText(_translate("Dialog", "Hinzufügen"))
        self.pushButton_3.setText(_translate("Dialog", "Ändern"))
        self.pushButton_2.setText(_translate("Dialog", "Löschen"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Art"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "D"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Gewicht"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Preis"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Var1"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Var2"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Var3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Materialparameter"))
        self.findButton.setText(_translate("Dialog", "Personen aus Auftragsdatenbank in\n"
" Personendatenbank überführen"))
        self.connectButton.setText(_translate("Dialog", "Connect to Database"))
        self.emailButton.setText(_translate("Dialog", "E-Mail testen"))
        self.closeConButton.setText(_translate("Dialog", "Close Connection"))
        self.openButton.setText(_translate("Dialog", "Daten aus Michaels \n"
"Auftragsprogramm(Excel) \n"
"überführen"))
        self.LoadButton.setText(_translate("Dialog", "Auftrags hilfsfunktion über \n"
"die Ordner(veraltet)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Zusatzfunktionen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
