# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Telefonbuch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Telefonbuch(object):
    def setupUi(self, Telefonbuch):
        Telefonbuch.setObjectName("Telefonbuch")
        Telefonbuch.resize(1700, 905)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Telefonbuch)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.l_vorname = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_vorname.setFont(font)
        self.l_vorname.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_vorname.setObjectName("l_vorname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l_vorname)
        self.label_3 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.l_nachname = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_nachname.setFont(font)
        self.l_nachname.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_nachname.setObjectName("l_nachname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_nachname)
        self.label_5 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.l_kostenstelle = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_kostenstelle.setFont(font)
        self.l_kostenstelle.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_kostenstelle.setObjectName("l_kostenstelle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l_kostenstelle)
        self.label_4 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.l_abteilung = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_abteilung.setFont(font)
        self.l_abteilung.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_abteilung.setObjectName("l_abteilung")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l_abteilung)
        self.label_6 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.l_telefon = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_telefon.setFont(font)
        self.l_telefon.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_telefon.setObjectName("l_telefon")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.l_telefon)
        self.label_7 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.l_email = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.l_email.setFont(font)
        self.l_email.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.l_email.setObjectName("l_email")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l_email)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deletebut = QtWidgets.QPushButton(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.deletebut.setFont(font)
        self.deletebut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.deletebut.setObjectName("deletebut")
        self.horizontalLayout.addWidget(self.deletebut)
        self.addbut = QtWidgets.QPushButton(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.addbut.setFont(font)
        self.addbut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.addbut.setObjectName("addbut")
        self.horizontalLayout.addWidget(self.addbut)
        self.savebut = QtWidgets.QPushButton(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.savebut.setFont(font)
        self.savebut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.savebut.setObjectName("savebut")
        self.horizontalLayout.addWidget(self.savebut)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_7 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #8daac4,\n"
"                     stop: 0.5 #5085b5, stop: 1.0 #226eb3);\n"
"}\n"
"QLineEdit:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:2px;\n"
"border-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchbut = QtWidgets.QPushButton(Telefonbuch)
        self.searchbut.setStyleSheet("QPushButton{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #c8def3, stop: 0.4 #79aee2,\n"
"                     stop: 0.5 #6fa3d6, stop: 1.0 #6798c7);\n"
"color:rgb(0, 0, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                     stop: 0 #6798c7, stop: 0.4 #6fa3d6,\n"
"                     stop: 0.5 #79aee2, stop: 1.0 #c8def3);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"border-color:rgb(46, 87, 143);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(200, 222, 243);\n"
"border-style:inset;\n"
"}\n"
"")
        self.searchbut.setObjectName("searchbut")
        self.horizontalLayout_2.addWidget(self.searchbut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Telefonbuch)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.personentable = QtWidgets.QTableWidget(Telefonbuch)
        font = QtGui.QFont()
        font.setFamily("VW Head CarUI")
        self.personentable.setFont(font)
        self.personentable.setObjectName("personentable")
        self.personentable.setColumnCount(7)
        self.personentable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.personentable.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.personentable)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.backToMainMenu = QtWidgets.QPushButton(Telefonbuch)
        self.backToMainMenu.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.backToMainMenu.setFont(font)
        self.backToMainMenu.setStyleSheet("QPushButton{\n"
"background: rgb(180,180,180);\n"
"border-radius:5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(220,220,220);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: green;\n"
"}\n"
"QPushButton:pressed{\n"
"background:rgb(255,255,255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"}")
        self.backToMainMenu.setObjectName("backToMainMenu")
        self.horizontalLayout_4.addWidget(self.backToMainMenu)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)

        self.retranslateUi(Telefonbuch)
        QtCore.QMetaObject.connectSlotsByName(Telefonbuch)

    def retranslateUi(self, Telefonbuch):
        _translate = QtCore.QCoreApplication.translate
        Telefonbuch.setWindowTitle(_translate("Telefonbuch", "Telefonbuch"))
        self.label_2.setText(_translate("Telefonbuch", "Vorname"))
        self.label_3.setText(_translate("Telefonbuch", "Nachname"))
        self.label_5.setText(_translate("Telefonbuch", "Kostenstelle"))
        self.label_4.setText(_translate("Telefonbuch", "Abteilung"))
        self.label_6.setText(_translate("Telefonbuch", "Telefon"))
        self.label_7.setText(_translate("Telefonbuch", "E-Mail"))
        self.deletebut.setText(_translate("Telefonbuch", "Löschen"))
        self.addbut.setText(_translate("Telefonbuch", "Hinzufügen"))
        self.savebut.setText(_translate("Telefonbuch", "Speichern"))
        self.label_8.setText(_translate("Telefonbuch", "Suchen"))
        self.label_9.setText(_translate("Telefonbuch", "Vorname"))
        self.label_10.setText(_translate("Telefonbuch", "Nachname"))
        self.label_11.setText(_translate("Telefonbuch", "Kostenstelle"))
        self.label_12.setText(_translate("Telefonbuch", "Abteilung"))
        self.label_13.setText(_translate("Telefonbuch", "Telefon"))
        self.label_14.setText(_translate("Telefonbuch", "E-Mail"))
        self.searchbut.setText(_translate("Telefonbuch", "Suchen"))
        self.label.setText(_translate("Telefonbuch", "Telefonbuch"))
        item = self.personentable.horizontalHeaderItem(0)
        item.setText(_translate("Telefonbuch", "ID"))
        item = self.personentable.horizontalHeaderItem(1)
        item.setText(_translate("Telefonbuch", "Nachname"))
        item = self.personentable.horizontalHeaderItem(2)
        item.setText(_translate("Telefonbuch", "Vorname"))
        item = self.personentable.horizontalHeaderItem(3)
        item.setText(_translate("Telefonbuch", "Abteilung"))
        item = self.personentable.horizontalHeaderItem(4)
        item.setText(_translate("Telefonbuch", "Kostenstelle"))
        item = self.personentable.horizontalHeaderItem(5)
        item.setText(_translate("Telefonbuch", "Telefon"))
        item = self.personentable.horizontalHeaderItem(6)
        item.setText(_translate("Telefonbuch", "E-Mail"))
        self.backToMainMenu.setText(_translate("Telefonbuch", "Zurück"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Telefonbuch = QtWidgets.QDialog()
    ui = Ui_Telefonbuch()
    ui.setupUi(Telefonbuch)
    Telefonbuch.show()
    sys.exit(app.exec_())
